#!/usr/bin/env python3
"""
Create Matterport-only rotation SFT training data for continue training.

Data sources (per Matterport viewpoint, produced by DialNav's
generate_matterport_rotation_qa.py --mode all):
  - rotation_qa_questions.json                  (legacy 4-image QA)
  - rotation_qa_questions_relational.json       (3-image CW-triple QA)
  - rotation_qa_questions_two_image.json        (2-image adjacent-pair QA)

Default sample split: 2000 (legacy) + 4000 (relational) + 3000 (two_image) = 9000.

Four thinking modes supported:
  --thinking_mode visual_only (default)
    walls + bridge as visual thinking target → Parquet files
    image_list length: 5 (legacy) / 4 (relational) / 3 (two_image)

  --thinking_mode no_thinking
    walls only, direct answer → JSONL (ShareGPT format)
    image count: 4 / 3 / 2

  --thinking_mode json_export
    walls + bridge copied to images/ → JSON file (for manual inspection)

  --thinking_mode text_thinking
    Reads pre-annotated matterport_rotation.jsonl from --text_thinking_source_file
    (generated by an annotation script) and writes text_thinking.jsonl.

  --thinking_mode interleaved
    Combines text-think + visual-think + answer. Reuses visual_only's wall+bridge
    images and prepends <think>{text}</think> to the first output text. Skips
    samples missing a think trace. Output: sharded parquet in <output_dir>/interleaved/.

Usage:
    python create_matterport_rotation_sft_data.py
    python create_matterport_rotation_sft_data.py --thinking_mode no_thinking
    python create_matterport_rotation_sft_data.py \\
        --n_legacy 2000 --n_relational 4000 --n_two_image 3000
"""

import argparse
import io
import json
import os
import random
import re
import shutil
from collections import Counter
from functools import partial

import pyarrow as pa
import pyarrow.parquet as pq
from PIL import Image
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor


VISUAL_ONLY_THINK_SYSTEM_PROMPT = (
    "Think visually to answer the question. "
    "Enclose your visual thinking within <image_start> </image_end>."
)

NO_THINKING_SYSTEM_PROMPT = (
    "Answer the question directly. "
    "Provide your final answer wrapped in <answer></answer> tags, "
    "i.e.<answer> answer here </answer>."
)

TEXT_THINKING_SYSTEM_PROMPT = (
    "Think step by step before answering. "
    "Enclose your thinking within <think> </think> tags. "
    "Provide your final answer wrapped in <answer></answer> tags, "
    "i.e.<answer> answer here </answer>."
)

INTERLEAVED_SYSTEM_PROMPT = (
    "Think step by step before answering, and use a visual sketch to support your reasoning. "
    "Enclose your text thinking within <think> </think> tags, then your visual thinking within "
    "<image_start> <image_end>. "
    "Provide your final answer wrapped in <answer></answer> tags, "
    "i.e.<answer> answer here </answer>."
)

THINK_RE = re.compile(r"<think>(.*?)</think>", re.DOTALL)


def _extract_human_question(human_val: str) -> str:
    last = human_val.rfind("<image>")
    tail = human_val[last + len("<image>"):] if last != -1 else human_val
    return tail.lstrip("\n").strip()


def build_think_lookup(jsonl_path: str):
    """Returns {(sample_id, question_text): think_text}."""
    lookup = {}
    if not os.path.exists(jsonl_path):
        print(f"  [warn] missing think source {jsonl_path}")
        return lookup
    with open(jsonl_path) as f:
        for ln in f:
            row = json.loads(ln)
            sid = row.get("id")
            convs = row.get("conversations", [])
            human = next((c["value"] for c in convs if c.get("from") == "human"), "")
            gpt   = next((c["value"] for c in convs if c.get("from") == "gpt"),   "")
            m = THINK_RE.search(gpt)
            if not (sid and m):
                continue
            lookup[(sid, _extract_human_question(human))] = m.group(1).strip()
    return lookup


def lookup_think(think_lookup, sample_id, question):
    qn = (question or "").strip()
    sid = sample_id or ""
    if (sid, qn) in think_lookup:
        return think_lookup[(sid, qn)]
    for (k_sid, k_q), think in think_lookup.items():
        if k_sid != sid:
            continue
        if k_q.startswith(qn) or qn.startswith(k_q):
            return think
    return None

MATTERPORT_ROTATION_QA_DIR = "/path/to/scratch/matterport_views"
DEFAULT_OUTPUT_DIR = "/path/to/scratch/infinigen/training_data_matterport_rotation"


# Per-mode configuration — drives loading + processing so the rest of the
# code is mode-agnostic.
MODE_CONFIG = {
    "legacy": {
        "filename":   "rotation_qa_questions.json",
        "n_walls":    4,
        "bridge_key": "bridge_panorama",
        "types": [
            "rotation_direction_mcq",
            "rotation_proximity_yesno",
        ],
    },
    "relational": {
        "filename":   "rotation_qa_questions_relational.json",
        "n_walls":    3,
        "bridge_key": "bridge",
        "types": [
            "relational_mcq",
            "relational_yesno",
            "turn_direction_mcq",
            "rotation_direction_mcq",
        ],
    },
    "two_image": {
        "filename":   "rotation_qa_questions_two_image.json",
        "n_walls":    2,
        "bridge_key": "bridge",
        "types": [
            "turn_direction_2img_mcq",
            "relational_2img_mcq",
        ],
    },
}


# ── Image loading ─────────────────────────────────────────────────────────────

def image_to_bytes(image_path: str) -> bytes:
    """Load image bytes. For PNG files, read raw bytes directly (no re-encode)."""
    try:
        if image_path.lower().endswith('.png'):
            with open(image_path, 'rb') as f:
                return f.read()
        with Image.open(image_path) as img:
            if img.mode in ('RGBA', 'P'):
                img = img.convert('RGB')
            byte_stream = io.BytesIO()
            img.save(byte_stream, format='PNG')
            return byte_stream.getvalue()
    except Exception as e:
        print(f"[ERROR] Failed to load image {image_path}: {e}")
        return None


def answer_for_sample(sample: dict) -> str:
    """Extract the training-target answer string for any question type.

    MCQ → letter (A/B/C/…). Yes/No → the stored string ("Yes"/"No").
    Works uniformly across all 8 question types across the three modes.
    """
    ci = sample.get("correct_index")
    if isinstance(ci, int):
        return chr(65 + ci)
    return sample.get("correct_answer", "")


# ── Loading / sampling ────────────────────────────────────────────────────────

def load_mode_samples(rotation_qa_dir: str, mode: str, scan_ids: set = None) -> list:
    """Walk the viewpoint tree and collect every question in the given mode's
    JSON file. Every returned dict carries `source_mode` plus the fields each
    processor needs. Silently skips viewpoints whose mode file is missing
    (useful while the SLURM generator is still running).

    If `scan_ids` is provided, only those scans are processed."""
    cfg = MODE_CONFIG[mode]
    if not os.path.exists(rotation_qa_dir):
        print(f"  [SKIP] Matterport rotation dir not found: {rotation_qa_dir}")
        return []

    samples = []
    allowed_types = set(cfg["types"])
    n_vp_seen = n_vp_loaded = 0
    for scan_id in sorted(os.listdir(rotation_qa_dir)):
        if scan_ids is not None and scan_id not in scan_ids:
            continue
        scan_dir = os.path.join(rotation_qa_dir, scan_id)
        if not os.path.isdir(scan_dir):
            continue
        for viewpoint_id in sorted(os.listdir(scan_dir)):
            vp_dir = os.path.join(scan_dir, viewpoint_id)
            if not os.path.isdir(vp_dir):
                continue
            n_vp_seen += 1
            qa_file = os.path.join(vp_dir, cfg["filename"])
            if not os.path.exists(qa_file):
                continue
            try:
                with open(qa_file, "r") as f:
                    data = json.load(f)
            except Exception as e:
                print(f"  [WARN] Failed to load {qa_file}: {e}")
                continue
            n_vp_loaded += 1
            scene_id = f"{scan_id}_{viewpoint_id}"
            for i, q in enumerate(data.get("rotation_questions", [])):
                qtype = q.get("question_type")
                if qtype not in allowed_types:
                    continue
                samples.append({
                    "sample_id":     f"matterport_{mode}_{scene_id}_{i}",
                    "source_mode":   mode,
                    "question_type": qtype,
                    "scene_id":      scene_id,
                    "vp_dir":        vp_dir,
                    "question":      q.get("question_text", ""),
                    "options":       q.get("options", []),
                    "correct_index": q.get("correct_index"),
                    "correct_answer": q.get("correct_answer", ""),
                    "images":        q.get("images", {}),
                })

    print(f"  [{mode}] scanned {n_vp_seen} viewpoints, loaded {n_vp_loaded}, "
          f"collected {len(samples)} questions")
    return samples


def sample_pool(pool: list, target: int, mode: str) -> list:
    if target <= 0:
        return []
    if len(pool) <= target:
        if len(pool) < target:
            print(f"  [WARN] {mode}: requested {target} but only {len(pool)} available; "
                  f"taking all.")
        return list(pool)
    return random.sample(pool, target)


# ── Per-sample processors ─────────────────────────────────────────────────────

def _wall_filenames_in_order(sample: dict, n_walls: int):
    """Ordered list of wall image filenames for a sample."""
    images = sample["images"]
    keys = [f"image_{i}" for i in range(1, n_walls + 1)]
    out = []
    for k in keys:
        fn = images.get(k)
        if not fn:
            return None, k
        out.append(fn)
    return out, None


def process_item_visual_only_rotation(sample: dict):
    """Walls in image_list, bridge appended as the visual-thinking target."""
    try:
        mode = sample["source_mode"]
        cfg  = MODE_CONFIG[mode]
        n    = cfg["n_walls"]
        sample_id = sample["sample_id"]
        vp_dir    = sample["vp_dir"]
        images    = sample["images"]

        wall_fns, missing = _wall_filenames_in_order(sample, n)
        if wall_fns is None:
            print(f"[WARN] {sample_id}: missing wall key {missing}")
            return None

        bridge_fn = images.get(cfg["bridge_key"])
        if not bridge_fn:
            print(f"[WARN] {sample_id}: missing bridge key {cfg['bridge_key']}")
            return None

        img_bytes_list = []
        for fn in wall_fns + [bridge_fn]:
            b = image_to_bytes(os.path.join(vp_dir, fn))
            if b is None:
                return None
            img_bytes_list.append(b)

        answer_text = answer_for_sample(sample)

        return {
            "image_list":       img_bytes_list,
            "instruction_list": [VISUAL_ONLY_THINK_SYSTEM_PROMPT + "\n" + sample["question"]],
            "output_text_list": [
                "<image_start>",
                f"<image_end><answer>{answer_text}</answer>",
            ],
            "sample_id": sample_id,
        }
    except Exception as e:
        print(f"[ERROR] {sample.get('sample_id', '?')}: {e}")
        import traceback
        traceback.print_exc()
        return None


def process_item_interleaved_rotation(sample: dict, think_lookup: dict):
    """Walls + bridge as visual-thinking target, with text think prepended."""
    try:
        mode = sample["source_mode"]
        cfg  = MODE_CONFIG[mode]
        n    = cfg["n_walls"]
        sample_id = sample["sample_id"]
        vp_dir    = sample["vp_dir"]
        images    = sample["images"]
        question  = sample["question"]

        think_text = lookup_think(think_lookup, sample_id, question)
        if think_text is None:
            return None

        wall_fns, missing = _wall_filenames_in_order(sample, n)
        if wall_fns is None:
            print(f"[WARN] {sample_id}: missing wall key {missing}")
            return None

        bridge_fn = images.get(cfg["bridge_key"])
        if not bridge_fn:
            print(f"[WARN] {sample_id}: missing bridge key {cfg['bridge_key']}")
            return None

        img_bytes_list = []
        for fn in wall_fns + [bridge_fn]:
            b = image_to_bytes(os.path.join(vp_dir, fn))
            if b is None:
                return None
            img_bytes_list.append(b)

        answer_text = answer_for_sample(sample)

        return {
            "image_list":       img_bytes_list,
            "instruction_list": [INTERLEAVED_SYSTEM_PROMPT + "\n" + question],
            "output_text_list": [
                f"<think>{think_text}</think><image_start>",
                f"<image_end><answer>{answer_text}</answer>",
            ],
            "sample_id": sample_id,
        }
    except Exception as e:
        print(f"[ERROR] {sample.get('sample_id', '?')}: {e}")
        import traceback
        traceback.print_exc()
        return None


def process_item_no_thinking_rotation(sample: dict, image_root_dir: str):
    """Walls only, direct answer. N wall images with N <image> tokens."""
    try:
        mode = sample["source_mode"]
        cfg  = MODE_CONFIG[mode]
        n    = cfg["n_walls"]
        sample_id = sample["sample_id"]
        vp_dir    = sample["vp_dir"]

        wall_fns, missing = _wall_filenames_in_order(sample, n)
        if wall_fns is None:
            print(f"[WARN] {sample_id}: missing wall key {missing}")
            return None

        img_paths = [os.path.join(vp_dir, fn) for fn in wall_fns]
        for p in img_paths:
            if not os.path.exists(p):
                print(f"[WARN] {sample_id}: image not found: {p}")
                return None

        rel_paths = [os.path.relpath(p, image_root_dir) for p in img_paths]
        image_tokens = "<image>" * n
        full_question = image_tokens + "\n" + sample["question"]
        user_message  = f"{NO_THINKING_SYSTEM_PROMPT}\n\n{full_question}"
        answer_text   = answer_for_sample(sample)

        return {
            "conversations": [
                {"from": "human", "value": user_message},
                {"from": "gpt",   "value": f"<answer>{answer_text}</answer>"},
            ],
            "image": rel_paths,
            "id":    sample_id,
        }
    except Exception as e:
        print(f"[ERROR] {sample.get('sample_id', '?')}: {e}")
        import traceback
        traceback.print_exc()
        return None


def process_item_json_export_matterport_rotation(sample: dict, images_dir: str):
    """Copy walls + bridge to images/ and emit a flat dict per sample.

    Schema is mode-aware: `images` is a list of N wall paths, `bridge` is
    the per-sample bridge path. No fixed image_1..image_4 keys.
    """
    try:
        mode = sample["source_mode"]
        cfg  = MODE_CONFIG[mode]
        n    = cfg["n_walls"]
        sample_id = sample["sample_id"]
        vp_dir    = sample["vp_dir"]
        images    = sample["images"]

        wall_fns, missing = _wall_filenames_in_order(sample, n)
        if wall_fns is None:
            print(f"[WARN] {sample_id}: missing wall key {missing}")
            return None

        bridge_fn = images.get(cfg["bridge_key"])
        if not bridge_fn:
            print(f"[WARN] {sample_id}: missing bridge key {cfg['bridge_key']}")
            return None

        dst_walls = []
        for idx, fn in enumerate(wall_fns, start=1):
            src = os.path.join(vp_dir, fn)
            if not os.path.exists(src):
                print(f"[WARN] {sample_id}: image not found: {src}")
                return None
            dst = os.path.join(images_dir, f"{sample_id}_image_{idx}.png")
            shutil.copy2(src, dst)
            dst_walls.append(f"images/{sample_id}_image_{idx}.png")

        bridge_src = os.path.join(vp_dir, bridge_fn)
        if not os.path.exists(bridge_src):
            print(f"[WARN] {sample_id}: bridge not found: {bridge_src}")
            return None
        bridge_dst = os.path.join(images_dir, f"{sample_id}_bridge.png")
        shutil.copy2(bridge_src, bridge_dst)
        bridge_rel = f"images/{sample_id}_bridge.png"

        answer_text = answer_for_sample(sample)

        return {
            "sample_id":     sample_id,
            "source_mode":   mode,
            "question_type": sample.get("question_type", ""),
            "scene_id":      sample.get("scene_id", ""),
            "images":        dst_walls,
            "bridge":        bridge_rel,
            "instruction":   VISUAL_ONLY_THINK_SYSTEM_PROMPT + "\n" + sample["question"],
            "output":        f"<image_start><image_end><answer>{answer_text}</answer>",
        }
    except Exception as e:
        print(f"[ERROR] {sample.get('sample_id', '?')}: {e}")
        import traceback
        traceback.print_exc()
        return None


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Create Matterport rotation SFT data (legacy + relational + two_image)"
    )
    parser.add_argument("--matterport_rotation_dir", default=MATTERPORT_ROTATION_QA_DIR)
    parser.add_argument("--output_dir", default=DEFAULT_OUTPUT_DIR)
    parser.add_argument(
        "--thinking_mode",
        choices=["visual_only", "no_thinking", "json_export", "text_thinking", "interleaved"],
        default="visual_only",
    )
    parser.add_argument(
        "--text_thinking_source_file",
        default=None,
        help="Path to pre-annotated matterport_rotation.jsonl for text_thinking mode. "
             "Defaults to <output_dir>/text_thinking/matterport_rotation.jsonl",
    )
    parser.add_argument(
        "--interleaved_text_file",
        default=None,
        help="Path to pre-annotated matterport_rotation.jsonl for interleaved mode. "
             "Defaults to <output_dir>/text_thinking/matterport_rotation.jsonl",
    )
    parser.add_argument("--n_legacy",     type=int, default=2000,
                        help="# samples from 4-image legacy QA (default 2000)")
    parser.add_argument("--n_relational", type=int, default=4000,
                        help="# samples from 3-image relational QA (default 4000)")
    parser.add_argument("--n_two_image",  type=int, default=3000,
                        help="# samples from 2-image two_image QA (default 3000)")
    parser.add_argument("--max_workers",  type=int, default=32)
    parser.add_argument("--rows_per_group",  type=int, default=10)
    parser.add_argument("--groups_per_file", type=int, default=10)
    parser.add_argument(
        "--image_root_dir",
        default="/network/scratch",
        help="Root dir for relative image paths (no_thinking mode only)",
    )
    parser.add_argument("--scan_ids", default=None,
                        help="comma-separated list of scan ids to restrict to")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    random.seed(args.seed)
    output_dir = os.path.join(args.output_dir, args.thinking_mode)
    print(f"Thinking mode: {args.thinking_mode}")
    print(f"Output dir:    {output_dir}")

    # ── text_thinking: load pre-annotated file ───────────────────────────────
    if args.thinking_mode == "text_thinking":
        src = args.text_thinking_source_file or os.path.join(
            args.output_dir, "text_thinking", "matterport_rotation.jsonl"
        )
        if not os.path.exists(src):
            print(f"[ERROR] source file not found: {src}")
            return
        all_data = [json.loads(ln) for ln in open(src)]
        for row in all_data:
            convs = row.get("conversations", [])
            if convs and convs[0].get("from") == "human":
                convs[0]["value"] = convs[0]["value"].replace(
                    NO_THINKING_SYSTEM_PROMPT, TEXT_THINKING_SYSTEM_PROMPT
                )
        random.shuffle(all_data)
        out_dir = os.path.join(args.output_dir, "text_thinking")
        os.makedirs(out_dir, exist_ok=True)
        out_file = os.path.join(out_dir, "text_thinking.jsonl")
        with open(out_file, "w") as f:
            for item in all_data:
                f.write(json.dumps(item) + "\n")
        print(f"\nDone! {len(all_data)} rows → {out_file}")
        return

    scan_id_set = None
    if args.scan_ids:
        scan_id_set = {s.strip() for s in args.scan_ids.split(",") if s.strip()}
        print(f"Restricting to {len(scan_id_set)} scans")

    mode_targets = {
        "legacy":     args.n_legacy,
        "relational": args.n_relational,
        "two_image":  args.n_two_image,
    }

    # ── Load + sample per mode ────────────────────────────────────────────────
    print("\nLoading Matterport rotation samples per mode...")
    all_samples = []
    for mode, target in mode_targets.items():
        if target <= 0:
            print(f"  [{mode}] target=0, skipping")
            continue
        pool = load_mode_samples(args.matterport_rotation_dir, mode, scan_ids=scan_id_set)
        picked = sample_pool(pool, target, mode)
        print(f"  [{mode}] sampled {len(picked)} / target {target} / pool {len(pool)}")
        all_samples.extend(picked)

    if not all_samples:
        print("No samples to process. Exiting.")
        return

    # Category breakdown (per-mode × per-type)
    print("\nCategory breakdown:")
    mode_counts = Counter(s["source_mode"] for s in all_samples)
    for mode, c in sorted(mode_counts.items()):
        print(f"  [{mode}] {c} samples")
        per_type = Counter(s["question_type"] for s in all_samples if s["source_mode"] == mode)
        for t, n in sorted(per_type.items()):
            print(f"      {t}: {n}")

    # ── Select processor ─────────────────────────────────────────────────────
    if args.thinking_mode == "no_thinking":
        process_fn = partial(process_item_no_thinking_rotation,
                             image_root_dir=args.image_root_dir)
    elif args.thinking_mode == "json_export":
        images_dir = os.path.join(output_dir, "images")
        os.makedirs(images_dir, exist_ok=True)
        process_fn = partial(process_item_json_export_matterport_rotation,
                             images_dir=images_dir)
    elif args.thinking_mode == "interleaved":
        src = args.interleaved_text_file or os.path.join(
            args.output_dir, "text_thinking", "matterport_rotation.jsonl"
        )
        print(f"\nBuilding think_lookup from {src}")
        think_lookup = build_think_lookup(src)
        print(f"  think_lookup: {len(think_lookup)} (sample_id, question) keys")
        process_fn = partial(process_item_interleaved_rotation, think_lookup=think_lookup)
    else:
        process_fn = process_item_visual_only_rotation

    print(f"\nProcessing {len(all_samples)} samples with {args.max_workers} workers...")
    with ThreadPoolExecutor(max_workers=args.max_workers) as executor:
        processed = list(tqdm(executor.map(process_fn, all_samples),
                              total=len(all_samples)))
    all_data = [r for r in processed if r is not None]
    random.shuffle(all_data)
    print(f"Successfully processed: {len(all_data)} samples")

    if not all_data:
        print("No samples to write. Exiting.")
        return

    os.makedirs(output_dir, exist_ok=True)

    # ── Write output ─────────────────────────────────────────────────────────
    if args.thinking_mode == "no_thinking":
        jsonl_file = os.path.join(output_dir, "no_thinking.jsonl")
        print(f"Writing JSONL to {jsonl_file}")
        with open(jsonl_file, "w") as f:
            for item in all_data:
                f.write(json.dumps(item) + "\n")
        print(f"\nDone! {len(all_data)} samples → {jsonl_file}")

    elif args.thinking_mode == "json_export":
        json_file = os.path.join(output_dir, "training_data.json")
        print(f"Writing JSON to {json_file}")
        with open(json_file, "w") as f:
            json.dump(all_data, f, indent=2)
        print(f"\nDone! {len(all_data)} samples → {json_file}")

    else:
        for item in all_data:
            item.pop("sample_id", None)

        schema = pa.schema([
            pa.field("image_list",       pa.list_(pa.binary())),
            pa.field("instruction_list", pa.list_(pa.string())),
            pa.field("output_text_list", pa.list_(pa.string())),
        ])

        rows_per_file = args.rows_per_group * args.groups_per_file
        file_index    = 0
        parquet_info  = {}

        print(f"Writing parquet files to {output_dir}")
        for i in tqdm(range(0, len(all_data), rows_per_file)):
            file_data = all_data[i:i + rows_per_file]
            parquet_file = os.path.join(output_dir, f"chunk_{file_index}.parquet")
            file_index += 1

            num_row_groups = 0
            with pq.ParquetWriter(parquet_file, schema=schema, version="2.6") as writer:
                for j in range(0, len(file_data), args.rows_per_group):
                    group_data = file_data[j:j + args.rows_per_group]
                    group_table = pa.Table.from_pylist(group_data, schema=schema)
                    writer.write_table(group_table)
                    num_row_groups += 1

            parquet_info[parquet_file] = {
                "num_row_groups": num_row_groups,
                "num_rows":       len(file_data),
            }

        parquet_info_path = os.path.join(output_dir, "parquet_info.json")
        with open(parquet_info_path, "w") as f:
            json.dump(parquet_info, f, indent=2)

        print(f"\nDone! {len(all_data)} samples → {file_index} parquet file(s) in {output_dir}")
        print(f"Parquet info: {parquet_info_path}")


if __name__ == "__main__":
    main()
