#!/usr/bin/env python3
"""
Create mixed SFT training data from existing panorama + V4 + V5 samples.

Three data sources:
  Existing: panorama_train_samples_filtered.json (panoramas in rendered_panorama_train/)
  V4: dataset_*_filtered_V4_normalized.json (panoramas in rendered_panorama_v4/)
  V5: dataset_*_filtered_V5_normalized.json (panoramas in rendered_panorama_v5/)

Supports four thinking modes:
  --thinking_mode visual_only (default)
    3 images: [cam0, cam1, panorama] → Parquet files
    Panorama is generated as intermediate thinking output.
    Skips samples without rendered panorama.

  --thinking_mode no_thinking
    2 images: [cam0, cam1] → JSONL (ShareGPT format)
    All samples included (no panorama needed).

  --thinking_mode understanding
    3 images: [cam0, cam1, panorama] as input → JSONL (ShareGPT format)
    Panorama provided as input context, output is answer only.
    Skips samples without rendered panorama.

  --thinking_mode text_thinking
    Reads pre-annotated per-category JSONL files from --text_thinking_source_dir
    (generated by annotate_text_reasoning.py) and merges them into
    text_thinking/text_thinking.jsonl. No raw data loading performed.

  --thinking_mode interleaved
    Combines text-thinking + visual-thinking. Builds a (sample_id, question)
    → think_text lookup from the same per-category files used by text_thinking,
    then runs the visual_only image pipeline. Each row's first output text is
    "<think>{text}</think><image_start>" instead of just "<image_start>".
    Output: sharded parquet files in <output_dir>/interleaved/.
    Samples missing a think trace OR a panorama are skipped.

Usage:
    python SpatialUnderstanding/data_creation/training_data/create_mix_all_sft_data.py
    python SpatialUnderstanding/data_creation/training_data/create_mix_all_sft_data.py \\
        --thinking_mode no_thinking
    python SpatialUnderstanding/data_creation/training_data/create_mix_all_sft_data.py \\
        --thinking_mode understanding
"""

import argparse
import io
import json
import os
import random
import re
import shutil
from functools import partial

import pyarrow as pa
import pyarrow.parquet as pq
from PIL import Image
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor


VISUAL_ONLY_THINK_SYSTEM_PROMPT = (
    "Think visually to answer the question. "
    "Enclose your visual thinking within <image_start> </image_end>."
)

NO_THINKING_SYSTEM_PROMPT = (
    "Answer the question directly. "
    "Provide your final answer wrapped in <answer></answer> tags, "
    "i.e.<answer> answer here </answer>."
)

TEXT_THINKING_SYSTEM_PROMPT = (
    "Think step by step before answering. "
    "Enclose your thinking within <think> </think> tags. "
    "Provide your final answer wrapped in <answer></answer> tags, "
    "i.e.<answer> answer here </answer>."
)

INTERLEAVED_SYSTEM_PROMPT = (
    "Think step by step before answering, and use a visual sketch to support your reasoning. "
    "Enclose your text thinking within <think> </think> tags, then your visual thinking within "
    "<image_start> <image_end>. "
    "Provide your final answer wrapped in <answer></answer> tags, "
    "i.e.<answer> answer here </answer>."
)

THINK_RE = re.compile(r"<think>(.*?)</think>", re.DOTALL)
ID_SUFFIX_RE = re.compile(r"_[a-z]+$")


def _extract_human_question(human_val: str) -> str:
    last = human_val.rfind("<image>")
    tail = human_val[last + len("<image>"):] if last != -1 else human_val
    return tail.lstrip("\n").strip()


def _strip_id_suffix(sid: str) -> str:
    """Remove trailing _a/_b/... suffix (added by rekey_text_thinking_dups.py)."""
    return ID_SUFFIX_RE.sub("", sid) if sid else sid


def build_think_lookup(jsonl_paths):
    """Returns {(base_sample_id, question_text): think_text}.
    Base id strips any _a/_b/... suffix; question text disambiguates the rest."""
    lookup = {}
    n_collide = 0
    for p in jsonl_paths:
        if not os.path.exists(p):
            print(f"  [skip] {p} missing")
            continue
        with open(p) as f:
            for ln in f:
                row = json.loads(ln)
                sid = _strip_id_suffix(row.get("id"))
                convs = row.get("conversations", [])
                human = next((c["value"] for c in convs if c.get("from") == "human"), "")
                gpt   = next((c["value"] for c in convs if c.get("from") == "gpt"),   "")
                m = THINK_RE.search(gpt)
                if not (sid and m):
                    continue
                key = (sid, _extract_human_question(human))
                if key in lookup:
                    n_collide += 1
                    continue
                lookup[key] = m.group(1).strip()
    if n_collide:
        print(f"  [warn] {n_collide} colliding (sample_id, question) keys; first wins")
    return lookup


def lookup_think(think_lookup, sample_id, question):
    qn = (question or "").strip()
    sid = sample_id or ""
    if (sid, qn) in think_lookup:
        return think_lookup[(sid, qn)]
    for (k_sid, k_q), think in think_lookup.items():
        if k_sid != sid:
            continue
        if k_q.startswith(qn) or qn.startswith(k_q):
            return think
    return None

UNDERSTANDING_SYSTEM_PROMPT = (
    "You are given two camera views and a panoramic overview of the scene. "
    "Answer the question directly. "
    "Provide your final answer wrapped in <answer></answer> tags, "
    "i.e.<answer> answer here </answer>."
)

UNDERSTANDING_ROTATION_SYSTEM_PROMPT = (
    "You are given four wall views and a panoramic overview of the scene. "
    "Answer the question directly. "
    "Provide your final answer wrapped in <answer></answer> tags, "
    "i.e.<answer> answer here </answer>."
)

# Existing panorama training data
EXISTING_TRAIN_FILE = "/path/to/scratch/VisualCoT/training_data/panorama_train_samples_filtered.json"
EXISTING_MAPPING_FILE = "/path/to/scratch/VisualCoT/training_data/scene_to_sample_id_filtered.json"
EXISTING_PANORAMA_DIR = "/path/to/scratch/VisualCoT/infinigen/rendered_panorama_train"

# V4 training data
V4_TRAIN_FILES = [
    "/path/to/scratch/infinigen/outputs_rendered/dataset_counting_questions_filtered_V4.json",
    "/path/to/scratch/infinigen/dataset_anchor_questions_filtered_V4_normalized.json",
    "/path/to/scratch/infinigen/dataset_spatial_questions_filtered_V4_normalized.json",
    "/path/to/scratch/infinigen/outputs_rendered/dataset_relative_distance_questions_filtered_V4.json",
    "/path/to/scratch/infinigen/dataset_perspective_taking_questions_filtered_V4_normalized.json",
]
V4_MAPPING_FILE = "/path/to/scratch/infinigen/scene_to_sample_id_v4_filtered.json"
V4_PANORAMA_DIR = "/path/to/scratch/infinigen/rendered_panorama_v4"

# V5 training data
V5_TRAIN_FILES = [
    "/path/to/scratch/infinigen/spatial/dataset_counting_questions_filtered_V5_normalized.json",
    "/path/to/scratch/infinigen/spatial/dataset_anchor_questions_filtered_V5_normalized.json",
    "/path/to/scratch/infinigen/spatial/dataset_spatial_questions_filtered_V5_normalized.json",
    "/path/to/scratch/infinigen/spatial/dataset_relative_distance_questions_filtered_V5.json",
    "/path/to/scratch/infinigen/spatial/dataset_perspective_taking_questions_filtered_V5_normalized.json",
]
V5_MAPPING_FILE = "/path/to/scratch/infinigen/scene_to_sample_id_v5_filtered.json"
V5_PANORAMA_DIR = "/path/to/scratch/infinigen/rendered_panorama_v5"

DEFAULT_OUTPUT_DIR = "/path/to/scratch/infinigen/training_data_mix_all_balance"

# Rotation QA data
ROTATION_QA_DIR = "/path/to/scratch/VisualCoT/novel_qa_rotation_spatial"

# Bad panorama blacklist (generated by filter_panoramas_vlm.py)
BAD_PANORAMAS_FILE = "/path/to/scratch/infinigen/bad_panoramas.json"


def remap_path(path: str) -> str:
    """Remap paths from home directories to network scratch."""
    if path is None:
        return None
    path = path.replace(
        "/path/to/scratch",
        "/path/to/scratch",
    )
    path = path.replace(
        "/path/to/scratch",
        "/path/to/scratch",
    )
    return path


SOURCE_PREFIXES = ("v4_", "v5_", "ankur_")


def infer_source_from_path(image_path: str) -> str:
    """Returns 'v4', 'v5', 'ankur', or 'unknown' from the image path.
    Mirrors annotate_text_reasoning.parse_source_from_image_path so the
    prefixed sample_id matches the source the annotator already records."""
    if not image_path:
        return "unknown"
    if "infinigen/spatial/" in image_path:
        return "v5"
    if "outputs_rendered/" in image_path:
        return "v4"
    if "spatial_collab_dataset/scenes/" in image_path:
        return "ankur"
    return "unknown"


def prefixed_sample_id(sample: dict) -> str:
    """Prefix sample_id with its source so V4/V5/ankur ids no longer collide.
    Idempotent: if sid already starts with a known source prefix, it's returned as-is."""
    sid = sample.get("sample_id", "")
    if not sid:
        return sid
    if sid.startswith(SOURCE_PREFIXES):
        return sid
    src = infer_source_from_path(sample.get("user_1_image_local_path", ""))
    return f"{src}_{sid}" if src != "unknown" else sid


def image_to_bytes(image_path: str) -> bytes:
    """Load image bytes. For PNG files, read raw bytes directly (no re-encode)."""
    try:
        if image_path.lower().endswith('.png'):
            with open(image_path, 'rb') as f:
                return f.read()
        with Image.open(image_path) as img:
            if img.mode in ('RGBA', 'P'):
                img = img.convert('RGB')
            byte_stream = io.BytesIO()
            img.save(byte_stream, format='PNG')
            return byte_stream.getvalue()
    except Exception as e:
        print(f"[ERROR] Failed to load image {image_path}: {e}")
        return None


def resolve_panorama_path(sample: dict,
                           existing_mapping: dict, v4_mapping: dict, v5_mapping: dict,
                           existing_panorama_dir: str, v4_panorama_dir: str, v5_panorama_dir: str) -> str:
    """Resolve panorama path: check existing mapping first, then V4, then V5."""
    scene_id = sample.get("scene_id")

    if scene_id in existing_mapping:
        first_sample_id = existing_mapping[scene_id]
        return os.path.join(existing_panorama_dir, scene_id, f"panorama_blender_limits_{first_sample_id}.png")

    if scene_id in v4_mapping:
        first_sample_id = v4_mapping[scene_id]
        return os.path.join(v4_panorama_dir, scene_id, f"panorama_blender_limits_{first_sample_id}.png")

    if scene_id in v5_mapping:
        first_sample_id = v5_mapping[scene_id]
        return os.path.join(v5_panorama_dir, scene_id, f"panorama_blender_limits_{first_sample_id}.png")

    return None


def get_question_and_answer(sample: dict):
    """Extract question, options, and answer index from a sample."""
    question = sample.get("question_both_views", "").strip()
    options_user_1 = sample.get("options_user_1")
    options_user_2 = sample.get("options_user_2")

    if options_user_1 is not None:
        options = options_user_1
        correct_answer_idx = sample.get("user_1_gt_answer_idx")
    elif options_user_2 is not None:
        options = options_user_2
        correct_answer_idx = sample.get("user_2_gt_answer_idx")
    else:
        options = sample.get("options", [])
        correct_answer_idx = sample.get("correct_answer_idx")

    if correct_answer_idx is not None:
        answer_text = chr(65 + correct_answer_idx)
    else:
        answer_text = sample.get("correct_answer", "").strip()

    return question, options, answer_text


def process_item_visual_only(sample: dict,
                              existing_mapping: dict, v4_mapping: dict, v5_mapping: dict,
                              existing_panorama_dir: str, v4_panorama_dir: str, v5_panorama_dir: str):
    """Visual-only thinking: 3 images (cam0, cam1, panorama) → Parquet row."""
    try:
        sample_id = sample.get("sample_id", "")
        question, options, answer_text = get_question_and_answer(sample)

        if not question or not answer_text:
            print(f"[WARNING] Missing question or answer for {sample_id}")
            return None

        img1_path = remap_path(sample.get("user_1_image_local_path"))
        img2_path = remap_path(sample.get("user_2_image_local_path"))
        panorama_path = resolve_panorama_path(
            sample, existing_mapping, v4_mapping, v5_mapping,
            existing_panorama_dir, v4_panorama_dir, v5_panorama_dir
        )

        if not all([img1_path, img2_path, panorama_path]):
            return None
        if not os.path.exists(panorama_path):
            return None  # Skip if panorama not rendered yet

        img1_bytes = image_to_bytes(img1_path)
        img2_bytes = image_to_bytes(img2_path)
        panorama_bytes = image_to_bytes(panorama_path)

        if not all([img1_bytes, img2_bytes, panorama_bytes]):
            print(f"[WARNING] Failed to load images for {sample_id}")
            return None

        if options:
            options_str = "\n".join([f"{chr(65 + i)}) {opt}" for i, opt in enumerate(options)])
            full_question = f"{question}\n\n{options_str}"
        else:
            full_question = question

        return {
            "image_list": [img1_bytes, img2_bytes, panorama_bytes],
            "instruction_list": [VISUAL_ONLY_THINK_SYSTEM_PROMPT + "\n" + full_question],
            "output_text_list": [
                "<image_start>",
                f"<image_end><answer>{answer_text}</answer>",
            ],
            "sample_id": sample_id,
        }

    except Exception as e:
        print(f"[ERROR] {sample.get('sample_id', 'unknown')}: {e}")
        import traceback
        traceback.print_exc()
        return None


def process_item_interleaved(sample: dict,
                              existing_mapping: dict, v4_mapping: dict, v5_mapping: dict,
                              existing_panorama_dir: str, v4_panorama_dir: str, v5_panorama_dir: str,
                              think_lookup: dict):
    """Interleaved: text think + visual think + answer. Same images as visual_only,
    output_text_list[0] prepends '<think>{text}</think>'."""
    try:
        sample_id = sample.get("sample_id", "")
        question, options, answer_text = get_question_and_answer(sample)

        if not question or not answer_text:
            return None

        think_text = lookup_think(think_lookup, sample_id, question)
        if think_text is None:
            return None  # no annotation

        img1_path = remap_path(sample.get("user_1_image_local_path"))
        img2_path = remap_path(sample.get("user_2_image_local_path"))
        panorama_path = resolve_panorama_path(
            sample, existing_mapping, v4_mapping, v5_mapping,
            existing_panorama_dir, v4_panorama_dir, v5_panorama_dir
        )

        if not all([img1_path, img2_path, panorama_path]):
            return None
        if not os.path.exists(panorama_path):
            return None

        img1_bytes = image_to_bytes(img1_path)
        img2_bytes = image_to_bytes(img2_path)
        panorama_bytes = image_to_bytes(panorama_path)

        if not all([img1_bytes, img2_bytes, panorama_bytes]):
            return None

        if options:
            options_str = "\n".join([f"{chr(65 + i)}) {opt}" for i, opt in enumerate(options)])
            full_question = f"{question}\n\n{options_str}"
        else:
            full_question = question

        return {
            "image_list": [img1_bytes, img2_bytes, panorama_bytes],
            "instruction_list": [INTERLEAVED_SYSTEM_PROMPT + "\n" + full_question],
            "output_text_list": [
                f"<think>{think_text}</think><image_start>",
                f"<image_end><answer>{answer_text}</answer>",
            ],
            "sample_id": sample_id,
        }

    except Exception as e:
        print(f"[ERROR] {sample.get('sample_id', 'unknown')}: {e}")
        import traceback
        traceback.print_exc()
        return None


def process_item_interleaved_rotation(sample: dict, think_lookup: dict):
    """Interleaved for rotation QA: 5 images (4 walls + bridge_panorama)."""
    try:
        sample_id = sample["sample_id"]

        correct_index = sample.get("correct_index")
        if sample["question_type"] == "rotation_direction_mcq":
            answer_text = chr(65 + correct_index) if correct_index is not None else sample["correct_answer"]
        else:
            answer_text = sample["correct_answer"]

        question = sample["question"]
        think_text = lookup_think(think_lookup, sample_id, question)
        if think_text is None:
            return None

        novel_qa_dir = sample["novel_qa_dir"]
        images = sample["images"]
        img_keys = ["image_1", "image_2", "image_3", "image_4", "bridge_panorama"]
        img_bytes_list = []
        for key in img_keys:
            filename = images.get(key)
            if not filename:
                return None
            path = os.path.join(novel_qa_dir, filename)
            b = image_to_bytes(path)
            if b is None:
                return None
            img_bytes_list.append(b)

        return {
            "image_list": img_bytes_list,
            "instruction_list": [INTERLEAVED_SYSTEM_PROMPT + "\n" + question],
            "output_text_list": [
                f"<think>{think_text}</think><image_start>",
                f"<image_end><answer>{answer_text}</answer>",
            ],
            "sample_id": sample_id,
        }

    except Exception as e:
        print(f"[ERROR] {sample.get('sample_id', 'unknown')}: {e}")
        import traceback
        traceback.print_exc()
        return None


def process_item_no_thinking(sample: dict, image_root_dir: str):
    """No thinking: 2 images (cam0, cam1) → JSONL row."""
    try:
        sample_id = sample.get("sample_id", "")
        question, options, answer_text = get_question_and_answer(sample)

        if not question or not answer_text:
            print(f"[WARNING] Missing question or answer for {sample_id}")
            return None

        img1_path = remap_path(sample.get("user_1_image_local_path"))
        img2_path = remap_path(sample.get("user_2_image_local_path"))

        if not all([img1_path, img2_path]):
            return None

        for img_path in [img1_path, img2_path]:
            if not os.path.exists(img_path):
                print(f"[WARNING] Image not found: {img_path}")
                return None

        rel_img1 = os.path.relpath(img1_path, image_root_dir)
        rel_img2 = os.path.relpath(img2_path, image_root_dir)

        if options:
            options_str = "\n".join([f"{chr(65 + i)}) {opt}" for i, opt in enumerate(options)])
            full_question = f"{question}\n\n{options_str}"
        else:
            full_question = question

        user_message = f"{NO_THINKING_SYSTEM_PROMPT}\n\n<image><image>\n{full_question}"
        assistant_response = f"<answer>{answer_text}</answer>"

        return {
            "conversations": [
                {"from": "human", "value": user_message},
                {"from": "gpt", "value": assistant_response},
            ],
            "image": [rel_img1, rel_img2],
            "id": sample_id,
        }

    except Exception as e:
        print(f"[ERROR] {sample.get('sample_id', 'unknown')}: {e}")
        import traceback
        traceback.print_exc()
        return None


def load_rotation_samples(rotation_qa_dir: str, n_mcq: int = 2, n_yesno: int = 1) -> list:
    """Walk rotation QA dir and sample n_mcq MCQ + n_yesno yesno per scene."""
    if not os.path.exists(rotation_qa_dir):
        print(f"  [SKIP] Rotation QA dir not found: {rotation_qa_dir}")
        return []

    samples = []
    for room_part in sorted(os.listdir(rotation_qa_dir)):
        room_dir = os.path.join(rotation_qa_dir, room_part)
        if not os.path.isdir(room_dir):
            continue
        for scene_id in sorted(os.listdir(room_dir)):
            qa_file = os.path.join(room_dir, scene_id, "novel_qa", "rotation_qa_questions.json")
            if not os.path.exists(qa_file):
                continue
            try:
                with open(qa_file, "r") as f:
                    data = json.load(f)
            except Exception as e:
                print(f"  [WARNING] Failed to load {qa_file}: {e}")
                continue

            questions = data.get("rotation_questions", [])
            mcq_qs = [q for q in questions if q.get("question_type") == "rotation_direction_mcq"]
            yesno_qs = [q for q in questions if q.get("question_type") == "rotation_proximity_yesno"]

            chosen = random.sample(mcq_qs, min(n_mcq, len(mcq_qs))) + \
                     random.sample(yesno_qs, min(n_yesno, len(yesno_qs)))

            novel_qa_dir = os.path.join(room_dir, scene_id, "novel_qa")
            for i, q in enumerate(chosen):
                samples.append({
                    "sample_id": f"rotation_{scene_id}_{i}",
                    "question_type": q["question_type"],
                    "scene_id": scene_id,
                    "novel_qa_dir": novel_qa_dir,
                    "question": q["question"],
                    "options": q.get("options", []),
                    "correct_index": q.get("correct_index"),
                    "correct_answer": q.get("correct_answer", ""),
                    "images": q.get("images", {}),
                })
    return samples


def process_item_visual_only_rotation(sample: dict):
    """Visual-only thinking for rotation QA: 5 images (4 walls + panorama) → Parquet row."""
    try:
        sample_id = sample["sample_id"]
        novel_qa_dir = sample["novel_qa_dir"]
        images = sample["images"]

        correct_index = sample.get("correct_index")
        if sample["question_type"] == "rotation_direction_mcq":
            answer_text = chr(65 + correct_index) if correct_index is not None else sample["correct_answer"]
        else:
            answer_text = sample["correct_answer"]  # "Yes" or "No"

        img_keys = ["image_1", "image_2", "image_3", "image_4", "bridge_panorama"]
        img_bytes_list = []
        for key in img_keys:
            filename = images.get(key)
            if not filename:
                print(f"[WARNING] Missing image key '{key}' for {sample_id}")
                return None
            path = os.path.join(novel_qa_dir, filename)
            b = image_to_bytes(path)
            if b is None:
                return None
            img_bytes_list.append(b)

        question = sample["question"]
        full_question = question

        return {
            "image_list": img_bytes_list,
            "instruction_list": [VISUAL_ONLY_THINK_SYSTEM_PROMPT + "\n" + full_question],
            "output_text_list": [
                "<image_start>",
                f"<image_end><answer>{answer_text}</answer>",
            ],
            "sample_id": sample_id,
        }

    except Exception as e:
        print(f"[ERROR] {sample.get('sample_id', 'unknown')}: {e}")
        import traceback
        traceback.print_exc()
        return None


def process_item_json_export(sample: dict,
                              existing_mapping: dict, v4_mapping: dict, v5_mapping: dict,
                              existing_panorama_dir: str, v4_panorama_dir: str, v5_panorama_dir: str,
                              images_dir: str):
    """JSON export: 3 images (cam0, cam1, panorama) copied to disk → JSON entry."""
    try:
        sample_id = sample.get("sample_id", "")
        question, options, answer_text = get_question_and_answer(sample)

        if not question or not answer_text:
            return None

        img1_path = remap_path(sample.get("user_1_image_local_path"))
        img2_path = remap_path(sample.get("user_2_image_local_path"))
        panorama_path = resolve_panorama_path(
            sample, existing_mapping, v4_mapping, v5_mapping,
            existing_panorama_dir, v4_panorama_dir, v5_panorama_dir
        )

        if not all([img1_path, img2_path, panorama_path]):
            return None
        if not os.path.exists(panorama_path):
            return None

        if options:
            opts_str = "\n".join([f"{chr(65 + i)}) {o}" for i, o in enumerate(options)])
            full_question = f"{question}\n\n{opts_str}"
        else:
            full_question = question

        shutil.copy2(img1_path, os.path.join(images_dir, f"{sample_id}_cam0.png"))
        shutil.copy2(img2_path, os.path.join(images_dir, f"{sample_id}_cam1.png"))
        shutil.copy2(panorama_path, os.path.join(images_dir, f"{sample_id}_panorama.png"))

        return {
            "sample_id": sample_id,
            "question_type": sample.get("question_type", ""),
            "scene_id": sample.get("scene_id", ""),
            "image_cam0": f"images/{sample_id}_cam0.png",
            "image_cam1": f"images/{sample_id}_cam1.png",
            "image_panorama": f"images/{sample_id}_panorama.png",
            "instruction": VISUAL_ONLY_THINK_SYSTEM_PROMPT + "\n" + full_question,
            "output": f"<image_start><image_end><answer>{answer_text}</answer>",
        }

    except Exception as e:
        print(f"[ERROR] {sample.get('sample_id', 'unknown')}: {e}")
        import traceback
        traceback.print_exc()
        return None


def process_item_json_export_rotation(sample: dict, images_dir: str):
    """JSON export for rotation QA: copies 5 images → JSON entry."""
    try:
        sample_id = sample["sample_id"]
        novel_qa_dir = sample["novel_qa_dir"]
        images = sample["images"]

        correct_index = sample.get("correct_index")
        if sample["question_type"] == "rotation_direction_mcq":
            answer_text = chr(65 + correct_index) if correct_index is not None else sample["correct_answer"]
        else:
            answer_text = sample["correct_answer"]

        img_keys = ["image_1", "image_2", "image_3", "image_4", "bridge_panorama"]
        dst_paths = []
        for key in img_keys:
            filename = images.get(key)
            if not filename:
                return None
            src = os.path.join(novel_qa_dir, filename)
            dst = os.path.join(images_dir, f"{sample_id}_{key}.png")
            shutil.copy2(src, dst)
            dst_paths.append(f"images/{sample_id}_{key}.png")

        question = sample["question"]
        full_question = question

        return {
            "sample_id": sample_id,
            "question_type": sample.get("question_type", ""),
            "scene_id": sample.get("scene_id", ""),
            "image_1": dst_paths[0],
            "image_2": dst_paths[1],
            "image_3": dst_paths[2],
            "image_4": dst_paths[3],
            "image_panorama": dst_paths[4],
            "instruction": VISUAL_ONLY_THINK_SYSTEM_PROMPT + "\n" + full_question,
            "output": f"<image_start><image_end><answer>{answer_text}</answer>",
        }

    except Exception as e:
        print(f"[ERROR] {sample.get('sample_id', 'unknown')}: {e}")
        import traceback
        traceback.print_exc()
        return None


def process_item_no_thinking_rotation(sample: dict, image_root_dir: str):
    """No thinking for rotation QA: 4 wall images → JSONL row."""
    try:
        sample_id = sample["sample_id"]
        novel_qa_dir = sample["novel_qa_dir"]
        images = sample["images"]

        correct_index = sample.get("correct_index")
        if sample["question_type"] == "rotation_direction_mcq":
            answer_text = chr(65 + correct_index) if correct_index is not None else sample["correct_answer"]
        else:
            answer_text = sample["correct_answer"]  # "Yes" or "No"

        img_keys = ["image_1", "image_2", "image_3", "image_4"]
        img_paths = []
        for key in img_keys:
            filename = images.get(key)
            if not filename:
                print(f"[WARNING] Missing image key '{key}' for {sample_id}")
                return None
            path = os.path.join(novel_qa_dir, filename)
            if not os.path.exists(path):
                print(f"[WARNING] Image not found: {path}")
                return None
            img_paths.append(path)

        rel_paths = [os.path.relpath(p, image_root_dir) for p in img_paths]
        question = sample["question"]
        full_question = "<image><image><image><image>\n" + question
        user_message = f"{NO_THINKING_SYSTEM_PROMPT}\n\n{full_question}"
        assistant_response = f"<answer>{answer_text}</answer>"

        return {
            "conversations": [
                {"from": "human", "value": user_message},
                {"from": "gpt", "value": assistant_response},
            ],
            "image": rel_paths,
            "id": sample_id,
        }

    except Exception as e:
        print(f"[ERROR] {sample.get('sample_id', 'unknown')}: {e}")
        import traceback
        traceback.print_exc()
        return None


def process_item_understanding(sample: dict,
                                existing_mapping: dict, v4_mapping: dict, v5_mapping: dict,
                                existing_panorama_dir: str, v4_panorama_dir: str, v5_panorama_dir: str,
                                image_root_dir: str):
    """Understanding: 3 images (cam0, cam1, panorama) as input → JSONL row with answer only."""
    try:
        sample_id = sample.get("sample_id", "")
        question, options, answer_text = get_question_and_answer(sample)

        if not question or not answer_text:
            print(f"[WARNING] Missing question or answer for {sample_id}")
            return None

        img1_path = remap_path(sample.get("user_1_image_local_path"))
        img2_path = remap_path(sample.get("user_2_image_local_path"))
        panorama_path = resolve_panorama_path(
            sample, existing_mapping, v4_mapping, v5_mapping,
            existing_panorama_dir, v4_panorama_dir, v5_panorama_dir
        )

        if not all([img1_path, img2_path, panorama_path]):
            return None
        for img_path in [img1_path, img2_path, panorama_path]:
            if not os.path.exists(img_path):
                return None

        rel_img1 = os.path.relpath(img1_path, image_root_dir)
        rel_img2 = os.path.relpath(img2_path, image_root_dir)
        rel_panorama = os.path.relpath(panorama_path, image_root_dir)

        if options:
            options_str = "\n".join([f"{chr(65 + i)}) {opt}" for i, opt in enumerate(options)])
            full_question = f"{question}\n\n{options_str}"
        else:
            full_question = question

        user_message = f"{UNDERSTANDING_SYSTEM_PROMPT}\n\n<image><image><image>\n{full_question}"
        assistant_response = f"<answer>{answer_text}</answer>"

        return {
            "conversations": [
                {"from": "human", "value": user_message},
                {"from": "gpt", "value": assistant_response},
            ],
            "image": [rel_img1, rel_img2, rel_panorama],
            "id": sample_id,
        }

    except Exception as e:
        print(f"[ERROR] {sample.get('sample_id', 'unknown')}: {e}")
        import traceback
        traceback.print_exc()
        return None


def process_item_understanding_rotation(sample: dict, image_root_dir: str):
    """Understanding for rotation QA: 5 images (4 walls + panorama) as input → JSONL row."""
    try:
        sample_id = sample["sample_id"]
        novel_qa_dir = sample["novel_qa_dir"]
        images = sample["images"]

        correct_index = sample.get("correct_index")
        if sample["question_type"] == "rotation_direction_mcq":
            answer_text = chr(65 + correct_index) if correct_index is not None else sample["correct_answer"]
        else:
            answer_text = sample["correct_answer"]  # "Yes" or "No"

        img_keys = ["image_1", "image_2", "image_3", "image_4", "bridge_panorama"]
        img_paths = []
        for key in img_keys:
            filename = images.get(key)
            if not filename:
                print(f"[WARNING] Missing image key '{key}' for {sample_id}")
                return None
            path = os.path.join(novel_qa_dir, filename)
            if not os.path.exists(path):
                print(f"[WARNING] Image not found: {path}")
                return None
            img_paths.append(path)

        rel_paths = [os.path.relpath(p, image_root_dir) for p in img_paths]
        question = sample["question"]
        full_question = "<image><image><image><image><image>\n" + question
        user_message = f"{UNDERSTANDING_ROTATION_SYSTEM_PROMPT}\n\n{full_question}"
        assistant_response = f"<answer>{answer_text}</answer>"

        return {
            "conversations": [
                {"from": "human", "value": user_message},
                {"from": "gpt", "value": assistant_response},
            ],
            "image": rel_paths,
            "id": sample_id,
        }

    except Exception as e:
        print(f"[ERROR] {sample.get('sample_id', 'unknown')}: {e}")
        import traceback
        traceback.print_exc()
        return None


def load_samples(filepath: str) -> list:
    if not os.path.exists(filepath):
        print(f"  [SKIP] Not found: {filepath}")
        return []
    with open(filepath, "r") as f:
        data = json.load(f)
    print(f"  Loaded {len(data)} samples from {os.path.basename(filepath)}")
    return data


def main():
    parser = argparse.ArgumentParser(
        description="Create mixed SFT training data from existing + V4 + V5 samples"
    )
    # Existing
    parser.add_argument("--existing_train_file", default=EXISTING_TRAIN_FILE)
    parser.add_argument("--existing_mapping_file", default=EXISTING_MAPPING_FILE)
    parser.add_argument("--existing_panorama_dir", default=EXISTING_PANORAMA_DIR)
    # V4
    parser.add_argument("--v4_train_files", nargs="+", default=V4_TRAIN_FILES)
    parser.add_argument("--v4_mapping_file", default=V4_MAPPING_FILE)
    parser.add_argument("--v4_panorama_dir", default=V4_PANORAMA_DIR)
    # V5
    parser.add_argument("--v5_train_files", nargs="+", default=V5_TRAIN_FILES)
    parser.add_argument("--v5_mapping_file", default=V5_MAPPING_FILE)
    parser.add_argument("--v5_panorama_dir", default=V5_PANORAMA_DIR)
    # Output
    parser.add_argument("--output_dir", default=DEFAULT_OUTPUT_DIR)
    parser.add_argument(
        "--thinking_mode",
        choices=["visual_only", "no_thinking", "understanding", "json_export", "text_thinking", "interleaved"],
        default="visual_only",
    )
    parser.add_argument(
        "--text_thinking_source_dir",
        default=None,
        help="Dir containing per-category annotated JSONL files for text_thinking mode. "
             "Defaults to <output_dir>/text_thinking/",
    )
    parser.add_argument(
        "--interleaved_text_dir",
        default=None,
        help="Dir containing per-category annotated JSONL files for interleaved mode. "
             "Defaults to <output_dir>/text_thinking/",
    )
    parser.add_argument("--max_workers", type=int, default=32)
    parser.add_argument("--rows_per_group", type=int, default=10)
    parser.add_argument("--groups_per_file", type=int, default=10)
    parser.add_argument(
        "--image_root_dir",
        default="/network/scratch",
        help="Root dir for relative image paths (no_thinking mode only)",
    )
    parser.add_argument("--rotation_qa_dir", default=ROTATION_QA_DIR)
    parser.add_argument("--no_rotation", action="store_true", default=False,
                        help="Exclude rotation QA from training data")
    parser.add_argument("--max_relative_distance", type=int, default=3000,
                        help="Max relative_distance questions to include (default: 3000). Set 0 for no cap.")
    parser.add_argument("--max_perspective_taking", type=int, default=3000,
                        help="Max perspective_taking+spatial_orientation combined (split 50/50, default: 3000). Set 0 for no cap.")
    parser.add_argument("--filter_subset", action=argparse.BooleanOptionalAction, default=False,
                        help="Keep only anchor + counting + relative distance (anchor-based closest/farthest "
                             "and camera-based closest_to_camera_*/farthest_from_camera_*). "
                             "Applied AFTER seeded sampling to preserve selection determinism.")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--prefix_ids",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Prefix sample_id with its source ('v4_'/'v5_'/'ankur_') so V4/V5/ankur "
             "namespaces no longer collide. Default: True.",
    )
    args = parser.parse_args()

    random.seed(args.seed)
    output_dir = os.path.join(args.output_dir, args.thinking_mode)
    print(f"Thinking mode: {args.thinking_mode}")
    print(f"Output dir: {output_dir}")

    # ── text_thinking: merge pre-annotated per-category files ────────────────
    if args.thinking_mode == "text_thinking":
        TEXT_THINKING_CATEGORIES = [
            "counting", "anchor", "relative_distance", "spatial", "perspective_taking",
        ]
        source_dir = args.text_thinking_source_dir or os.path.join(
            args.output_dir, "text_thinking"
        )
        print(f"Reading annotated files from: {source_dir}")
        all_data = []
        counts = {}
        for cat in TEXT_THINKING_CATEGORIES:
            path = os.path.join(source_dir, f"{cat}.jsonl")
            if not os.path.exists(path):
                print(f"  [skip] {path} missing")
                continue
            rows = [json.loads(ln) for ln in open(path)]
            for row in rows:
                convs = row.get("conversations", [])
                if convs and convs[0].get("from") == "human":
                    convs[0]["value"] = convs[0]["value"].replace(
                        NO_THINKING_SYSTEM_PROMPT, TEXT_THINKING_SYSTEM_PROMPT
                    )
            counts[cat] = len(rows)
            all_data.extend(rows)
            print(f"  {cat}: {len(rows)} rows")
        random.shuffle(all_data)
        out_dir = os.path.join(args.output_dir, "text_thinking")
        os.makedirs(out_dir, exist_ok=True)
        out_file = os.path.join(out_dir, "text_thinking.jsonl")
        with open(out_file, "w") as f:
            for item in all_data:
                f.write(json.dumps(item) + "\n")
        manifest = {
            "output": out_file,
            "total_rows": len(all_data),
            "rows_per_category": counts,
        }
        with open(os.path.join(out_dir, "manifest.json"), "w") as f:
            json.dump(manifest, f, indent=2)
        print(f"\nDone! {len(all_data)} rows → {out_file}")
        return

    # Load existing samples
    print(f"\nLoading existing panorama training samples...")
    existing_samples = load_samples(args.existing_train_file)

    # Load V4 samples
    print(f"\nLoading V4 training samples...")
    v4_samples = []
    for filepath in args.v4_train_files:
        v4_samples.extend(load_samples(filepath))
    print(f"  Total V4: {len(v4_samples)} samples")

    # Load V5 samples
    print(f"\nLoading V5 training samples...")
    v5_samples = []
    for filepath in args.v5_train_files:
        v5_samples.extend(load_samples(filepath))
    print(f"  Total V5: {len(v5_samples)} samples")

    # Load rotation QA samples
    rotation_samples = []
    if not args.no_rotation:
        print("\nLoading rotation QA samples...")
        rotation_samples = load_rotation_samples(args.rotation_qa_dir)
        print(f"  Rotation QA: {len(rotation_samples)} samples")

    all_samples = existing_samples + v4_samples + v5_samples
    print(f"\nTotal combined (non-rotation): {len(all_samples)} samples")

    # Load mappings
    existing_mapping = {}
    if os.path.exists(args.existing_mapping_file):
        with open(args.existing_mapping_file, "r") as f:
            existing_mapping = json.load(f)
        print(f"Existing mapping: {len(existing_mapping)} scenes")

    v4_mapping = {}
    if os.path.exists(args.v4_mapping_file):
        with open(args.v4_mapping_file, "r") as f:
            v4_mapping = json.load(f)
        print(f"V4 mapping: {len(v4_mapping)} scenes")

    v5_mapping = {}
    if os.path.exists(args.v5_mapping_file):
        with open(args.v5_mapping_file, "r") as f:
            v5_mapping = json.load(f)
        print(f"V5 mapping: {len(v5_mapping)} scenes")

    # Filter samples with valid questions
    all_samples = [s for s in all_samples if s.get("question_both_views", "").strip()]
    print(f"After question filter: {len(all_samples)} samples")

    # Filter out samples with bad panoramas (if blacklist exists)
    bad_panoramas = set()
    if os.path.exists(BAD_PANORAMAS_FILE):
        with open(BAD_PANORAMAS_FILE) as f:
            bad_panoramas = set(json.load(f).get("bad_panoramas", []))
        print(f"Loaded {len(bad_panoramas)} bad panoramas from blacklist")

        def _has_bad_panorama(sample):
            path = resolve_panorama_path(
                sample, existing_mapping, v4_mapping, v5_mapping,
                args.existing_panorama_dir, args.v4_panorama_dir, args.v5_panorama_dir
            )
            return path in bad_panoramas

        before = len(all_samples)
        all_samples = [s for s in all_samples if not _has_bad_panorama(s)]
        print(f"After bad panorama filter: {len(all_samples)} samples (removed {before - len(all_samples)})")

    # Source-prefix sample_ids so V4/V5/ankur namespaces stop colliding.
    # Apply BEFORE caps/shuffles so prefixed ids propagate everywhere downstream.
    if args.prefix_ids:
        n_prefixed = 0
        n_unknown = 0
        for s in all_samples:
            sid = s.get("sample_id", "")
            new_sid = prefixed_sample_id(s)
            if new_sid != sid:
                s["sample_id"] = new_sid
                n_prefixed += 1
            elif sid and not new_sid.startswith(SOURCE_PREFIXES):
                n_unknown += 1
        print(f"prefix_ids: prefixed {n_prefixed}, unknown source for {n_unknown}")

    # Balance relative_distance questions: sample max_relative_distance/2 from each group.
    # Group 1 (anchor): closest + farthest (object-anchor questions)
    # Group 2 (camera): closest_to_camera_* + farthest_from_camera_* (camera-position questions)
    if args.max_relative_distance > 0:
        anchor_types = {"closest", "farthest", "relative_distance"}
        camera_types = {"closest_to_camera_1", "closest_to_camera_2",
                        "farthest_from_camera_1", "farthest_from_camera_2"}
        anchor_qs = [s for s in all_samples if s.get("question_type") in anchor_types]
        camera_qs = [s for s in all_samples if s.get("question_type") in camera_types]
        other = [s for s in all_samples if s.get("question_type") not in anchor_types | camera_types]
        n_each = args.max_relative_distance // 2
        if len(anchor_qs) > n_each:
            anchor_qs = random.sample(anchor_qs, n_each)
        if len(camera_qs) > n_each:
            camera_qs = random.sample(camera_qs, n_each)
        print(f"relative_distance: {len(anchor_qs)} anchor + {len(camera_qs)} camera = {len(anchor_qs)+len(camera_qs)} total (cap={args.max_relative_distance})")
        all_samples = other + anchor_qs + camera_qs

    # Cap perspective_taking + spatial_orientation combined to max_perspective_taking total, split 50/50
    if args.max_perspective_taking > 0:
        persp_qs = [s for s in all_samples if s.get("question_type") == "perspective_taking"]
        spatial_qs = [s for s in all_samples if s.get("question_type") == "spatial_orientation"]
        other = [s for s in all_samples if s.get("question_type") not in ("perspective_taking", "spatial_orientation")]
        n_each = args.max_perspective_taking // 2
        if len(persp_qs) > n_each:
            persp_qs = random.sample(persp_qs, n_each)
        if len(spatial_qs) > n_each:
            spatial_qs = random.sample(spatial_qs, n_each)
        print(f"perspective_taking+spatial_orientation: {len(persp_qs)}+{len(spatial_qs)}={len(persp_qs)+len(spatial_qs)} total (cap={args.max_perspective_taking})")
        all_samples = other + persp_qs + spatial_qs

    # Subset filter: keep only anchor + counting + relative distance (anchor-based and camera-based).
    # Runs AFTER the seeded sampling above so selection of which rows survive is deterministic.
    if args.filter_subset:
        keep_types = {
            "anchor", "counting",
            "closest", "farthest",
            "closest_to_camera_1", "closest_to_camera_2",
            "farthest_from_camera_1", "farthest_from_camera_2",
        }
        before = len(all_samples)
        all_samples = [s for s in all_samples if s.get("question_type") in keep_types]
        print(f"After filter_subset (keep {sorted(keep_types)}): {len(all_samples)} samples (removed {before - len(all_samples)})")

    # Category breakdown (before processing)
    category_counts = {}
    for s in all_samples + rotation_samples:
        qtype = s.get("question_type", "unknown")
        category_counts[qtype] = category_counts.get(qtype, 0) + 1
    print("\nCategory breakdown:")
    for cat, count in sorted(category_counts.items()):
        print(f"  {cat}: {count}")

    # Select processor
    if args.thinking_mode == "no_thinking":
        process_fn = partial(process_item_no_thinking, image_root_dir=args.image_root_dir)
        process_fn_rotation = partial(process_item_no_thinking_rotation, image_root_dir=args.image_root_dir)
    elif args.thinking_mode == "understanding":
        process_fn = partial(
            process_item_understanding,
            existing_mapping=existing_mapping,
            v4_mapping=v4_mapping,
            v5_mapping=v5_mapping,
            existing_panorama_dir=args.existing_panorama_dir,
            v4_panorama_dir=args.v4_panorama_dir,
            v5_panorama_dir=args.v5_panorama_dir,
            image_root_dir=args.image_root_dir,
        )
        process_fn_rotation = partial(process_item_understanding_rotation, image_root_dir=args.image_root_dir)
    elif args.thinking_mode == "json_export":
        images_dir = os.path.join(output_dir, "images")
        os.makedirs(images_dir, exist_ok=True)
        process_fn = partial(
            process_item_json_export,
            existing_mapping=existing_mapping,
            v4_mapping=v4_mapping,
            v5_mapping=v5_mapping,
            existing_panorama_dir=args.existing_panorama_dir,
            v4_panorama_dir=args.v4_panorama_dir,
            v5_panorama_dir=args.v5_panorama_dir,
            images_dir=images_dir,
        )
        process_fn_rotation = partial(process_item_json_export_rotation, images_dir=images_dir)
    elif args.thinking_mode == "interleaved":
        text_dir = args.interleaved_text_dir or os.path.join(args.output_dir, "text_thinking")
        cat_files = [os.path.join(text_dir, f"{c}.jsonl")
                     for c in ["counting", "anchor", "relative_distance", "spatial", "perspective_taking"]]
        print(f"\nBuilding think_lookup from {text_dir}")
        think_lookup = build_think_lookup(cat_files)
        print(f"  think_lookup: {len(think_lookup)} (sample_id, question) keys")
        process_fn = partial(
            process_item_interleaved,
            existing_mapping=existing_mapping,
            v4_mapping=v4_mapping,
            v5_mapping=v5_mapping,
            existing_panorama_dir=args.existing_panorama_dir,
            v4_panorama_dir=args.v4_panorama_dir,
            v5_panorama_dir=args.v5_panorama_dir,
            think_lookup=think_lookup,
        )
        process_fn_rotation = partial(process_item_interleaved_rotation, think_lookup=think_lookup)
    else:
        process_fn = partial(
            process_item_visual_only,
            existing_mapping=existing_mapping,
            v4_mapping=v4_mapping,
            v5_mapping=v5_mapping,
            existing_panorama_dir=args.existing_panorama_dir,
            v4_panorama_dir=args.v4_panorama_dir,
            v5_panorama_dir=args.v5_panorama_dir,
        )
        process_fn_rotation = process_item_visual_only_rotation

    # Process non-rotation samples in parallel
    print(f"\nProcessing {len(all_samples)} samples with {args.max_workers} workers...")
    with ThreadPoolExecutor(max_workers=args.max_workers) as executor:
        processed = list(tqdm(executor.map(process_fn, all_samples), total=len(all_samples)))
    all_data = [res for res in processed if res is not None]

    # Process rotation samples in parallel
    if rotation_samples:
        print(f"\nProcessing {len(rotation_samples)} rotation QA samples...")
        with ThreadPoolExecutor(max_workers=args.max_workers) as executor:
            processed_rot = list(tqdm(executor.map(process_fn_rotation, rotation_samples), total=len(rotation_samples)))
        all_data += [res for res in processed_rot if res is not None]

    random.shuffle(all_data)
    print(f"Successfully processed: {len(all_data)} samples")

    if len(all_data) == 0:
        print("No samples to write. Exiting.")
        return

    os.makedirs(output_dir, exist_ok=True)

    if args.thinking_mode in ("no_thinking", "understanding"):
        jsonl_file = os.path.join(output_dir, f"{args.thinking_mode}.jsonl")
        print(f"Writing JSONL to {jsonl_file}")
        with open(jsonl_file, "w") as f:
            for item in all_data:
                f.write(json.dumps(item) + "\n")
        print(f"\nDone! {len(all_data)} samples → {jsonl_file}")

    elif args.thinking_mode == "json_export":
        json_file = os.path.join(output_dir, "training_data.json")
        print(f"Writing JSON to {json_file}")
        with open(json_file, "w") as f:
            json.dump(all_data, f, indent=2)
        print(f"\nDone! {len(all_data)} samples → {json_file}")

    else:
        # Remove sample_id before writing parquet
        for item in all_data:
            item.pop("sample_id", None)

        schema = pa.schema([
            pa.field("image_list", pa.list_(pa.binary())),
            pa.field("instruction_list", pa.list_(pa.string())),
            pa.field("output_text_list", pa.list_(pa.string())),
        ])

        rows_per_file = args.rows_per_group * args.groups_per_file
        file_index = 0
        parquet_info = {}

        print(f"Writing parquet files to {output_dir}")
        for i in tqdm(range(0, len(all_data), rows_per_file)):
            file_data = all_data[i:i + rows_per_file]
            parquet_file = os.path.join(output_dir, f"chunk_{file_index}.parquet")
            file_index += 1

            num_row_groups = 0
            with pq.ParquetWriter(parquet_file, schema=schema, version="2.6") as writer:
                for j in range(0, len(file_data), args.rows_per_group):
                    group_data = file_data[j:j + args.rows_per_group]
                    group_table = pa.Table.from_pylist(group_data, schema=schema)
                    writer.write_table(group_table)
                    num_row_groups += 1

            parquet_info[parquet_file] = {
                "num_row_groups": num_row_groups,
                "num_rows": len(file_data),
            }

        parquet_info_path = os.path.join(output_dir, "parquet_info.json")
        with open(parquet_info_path, "w") as f:
            json.dump(parquet_info, f, indent=2)

        print(f"\nDone! {len(all_data)} samples → {file_index} parquet file(s) in {output_dir}")
        print(f"Parquet info: {parquet_info_path}")


if __name__ == "__main__":
    main()
