#!/usr/bin/env python3
"""
Create point-matching SFT training data from the novel_qa_point_matching
outputs (v00 / v4 / v5).

Per-question inputs produced by generate_point_matching_qa.py:
    <output_dir>/<room_part>/<scene_id>/novel_qa/
        point_matching_qa_questions.json
        point_matching_img1_marked_<i>.png      # REF in Image 1
        point_matching_img2_marked_<i>.png      # A/B/C/D in Image 2
        point_matching_bridge_<i>.png           # optional panoramic bridge

Four thinking modes (modelled on create_matterport_rotation_sft_data.py):

  --thinking_mode visual_only (default)
    [img1_marked, img2_marked, bridge] → bridge is the visual-thinking target.
    Requires a panoramic bridge; questions without one are skipped.
    Output: sharded parquet files.

  --thinking_mode no_thinking
    [img1_marked, img2_marked] → direct answer.
    Output: JSONL in ShareGPT format.

  --thinking_mode json_export
    Copy img1/img2/bridge (if any) to images/ and emit a flat JSON for
    manual inspection.

  --thinking_mode text_thinking
    Reads pre-annotated point_matching.jsonl from --text_thinking_source_file
    (generated by annotate_point_matching_text_reasoning.py) and writes
    text_thinking.jsonl.

  --thinking_mode interleaved
    [img1_marked, img2_marked, bridge] with text-think + visual-think prefix.
    Pulls <think>...</think> from --interleaved_text_file and emits parquet
    rows with output_text_list = ["<think>...</think><image_start>",
    "<image_end><answer>X</answer>"]. Bridge required.

Usage:
    python create_point_matching_sft_data.py
    python create_point_matching_sft_data.py --thinking_mode no_thinking
    python create_point_matching_sft_data.py \\
        --n_v00 5000 --n_v4 500 --n_v5 1000
"""

import argparse
import io
import json
import os
import random
import re
import shutil
from collections import Counter
from concurrent.futures import ThreadPoolExecutor
from functools import partial

import pyarrow as pa
import pyarrow.parquet as pq
from PIL import Image
from tqdm import tqdm


VISUAL_ONLY_THINK_SYSTEM_PROMPT = (
    "Think visually to answer the question. "
    "Enclose your visual thinking within <image_start> </image_end>."
)

NO_THINKING_SYSTEM_PROMPT = (
    "Answer the question directly. "
    "Provide your final answer wrapped in <answer></answer> tags, "
    "i.e.<answer> answer here </answer>."
)

TEXT_THINKING_SYSTEM_PROMPT = (
    "Think step by step before answering. "
    "Enclose your thinking within <think> </think> tags. "
    "Provide your final answer wrapped in <answer></answer> tags, "
    "i.e.<answer> answer here </answer>."
)

INTERLEAVED_SYSTEM_PROMPT = (
    "Think step by step before answering, and use a visual sketch to support your reasoning. "
    "Enclose your text thinking within <think> </think> tags, then your visual thinking within "
    "<image_start> <image_end>. "
    "Provide your final answer wrapped in <answer></answer> tags, "
    "i.e.<answer> answer here </answer>."
)

THINK_RE = re.compile(r"<think>(.*?)</think>", re.DOTALL)


def _extract_human_question(human_val: str) -> str:
    """Recover the question text from the annotated human turn.
    Annotated format: '{SYSTEM_PROMPT}\\n\\n<image>...<image>\\n{question}'.
    Returns the substring after the last '<image>' (stripped)."""
    last = human_val.rfind("<image>")
    tail = human_val[last + len("<image>"):] if last != -1 else human_val
    return tail.lstrip("\n").strip()


def build_think_lookup(jsonl_path: str) -> dict:
    """Returns {(sample_id, question_text): think_text}."""
    lookup = {}
    n_collide = 0
    if not os.path.exists(jsonl_path):
        print(f"  [warn] interleaved source missing: {jsonl_path}")
        return lookup
    with open(jsonl_path) as f:
        for ln in f:
            row = json.loads(ln)
            sid = row.get("id")
            convs = row.get("conversations", [])
            human = next((c["value"] for c in convs if c.get("from") == "human"), "")
            gpt   = next((c["value"] for c in convs if c.get("from") == "gpt"),   "")
            m = THINK_RE.search(gpt)
            if not (sid and m):
                continue
            key = (sid, _extract_human_question(human))
            if key in lookup:
                n_collide += 1
                continue
            lookup[key] = m.group(1).strip()
    if n_collide:
        print(f"  [warn] {n_collide} colliding (id, question) keys; first wins")
    return lookup


def lookup_think(think_lookup: dict, sample_id: str, question: str):
    qn = (question or "").strip()
    sid = sample_id or ""
    if (sid, qn) in think_lookup:
        return think_lookup[(sid, qn)]
    for (k_sid, k_q), think in think_lookup.items():
        if k_sid != sid:
            continue
        if k_q.startswith(qn) or qn.startswith(k_q):
            return think
    return None

DEFAULT_OUTPUT_DIR = "/path/to/scratch/infinigen/training_data_point_matching"

DEFAULT_PANORAMA_ROOTS = [
    "/path/to/scratch/infinigen/rendered_panorama_v4",
    "/path/to/scratch/infinigen/rendered_panorama_v5",
    "/path/to/scratch/VisualCoT/infinigen/rendered_panorama_anchor_normalized",
    "/path/to/scratch/infinigen/rendered_panorama_point_matching",
    "/path/to/scratch/VisualCoT/infinigen/rendered_panorama_train",
    "/path/to/scratch/VisualCoT/infinigen/rendered_panorama_counting_normalized",
    "/path/to/scratch/VisualCoT/infinigen/rendered_panorama_map_questions_normalized",
    "/path/to/scratch/VisualCoT/infinigen/rendered_panorama_relative_direction_normalized",
    "/path/to/scratch/VisualCoT/infinigen/rendered_panorama_relative_distance_normalized",
]

# Per-source QA roots and tags.
SOURCE_CONFIG = {
    "v00": {
        "root": "/path/to/scratch/VisualCoT/novel_qa_point_matching",
    },
    "v4": {
        "root": "/path/to/scratch/VisualCoT/novel_qa_point_matching_v4",
    },
    "v5": {
        "root": "/path/to/scratch/VisualCoT/novel_qa_point_matching_v5",
    },
}


# ── Panorama index ───────────────────────────────────────────────────────────

def build_panorama_index(roots: list) -> dict:
    """Walk roots and return {scene_id: panorama_png_path}. First match wins."""
    index = {}
    for root in roots:
        if not os.path.isdir(root):
            continue
        for entry in os.scandir(root):
            if not entry.is_dir() or entry.name in index:
                continue
            pngs = [f.path for f in os.scandir(entry.path)
                    if f.name.startswith("panorama_") and f.name.endswith(".png")]
            if pngs:
                index[entry.name] = pngs[0]
    return index


# ── Image loading ─────────────────────────────────────────────────────────────

def image_to_bytes(image_path: str) -> bytes:
    """Load image bytes. For PNGs, read raw (no re-encode)."""
    try:
        if image_path.lower().endswith(".png"):
            with open(image_path, "rb") as f:
                return f.read()
        with Image.open(image_path) as img:
            if img.mode in ("RGBA", "P"):
                img = img.convert("RGB")
            buf = io.BytesIO()
            img.save(buf, format="PNG")
            return buf.getvalue()
    except Exception as e:
        print(f"[ERROR] Failed to load image {image_path}: {e}")
        return None


def answer_for_sample(sample: dict) -> str:
    ci = sample.get("correct_index")
    if isinstance(ci, int):
        return chr(65 + ci)
    return sample.get("correct_answer", "")


# ── Loading / sampling ────────────────────────────────────────────────────────

def load_source_samples(source: str, root: str, panorama_index: dict = None) -> list:
    """Walk <root>/<room_part>/<scene_id>/novel_qa/ and collect every question.

    Drops questions whose marked image 1 or image 2 PNG is missing on disk.
    bridge_path is set from (in priority order):
      1. pre-generated point_matching_bridge_<i>.png in novel_qa/
      2. raw panorama PNG looked up by scene_id in panorama_index
    """
    if not os.path.isdir(root):
        print(f"  [{source}] root not found: {root}")
        return []

    samples = []
    n_scene_seen = n_scene_loaded = 0
    for room_part in sorted(os.listdir(root)):
        room_dir = os.path.join(root, room_part)
        if not os.path.isdir(room_dir):
            continue
        for scene_id in sorted(os.listdir(room_dir)):
            scene_dir = os.path.join(room_dir, scene_id)
            if not os.path.isdir(scene_dir):
                continue
            n_scene_seen += 1
            qa_file = os.path.join(scene_dir, "novel_qa", "point_matching_qa_questions.json")
            if not os.path.exists(qa_file):
                continue
            try:
                with open(qa_file, "r") as f:
                    data = json.load(f)
            except Exception as e:
                print(f"  [WARN] Failed to load {qa_file}: {e}")
                continue
            n_scene_loaded += 1
            novel_qa_dir = os.path.dirname(qa_file)
            for i, q in enumerate(data.get("point_matching_questions", [])):
                imgs = q.get("images") or {}
                img1 = imgs.get("img1_marked")
                img2 = imgs.get("img2_marked")
                bridge = imgs.get("bridge")
                if not (img1 and img2):
                    continue
                img1_abs = os.path.join(novel_qa_dir, img1)
                img2_abs = os.path.join(novel_qa_dir, img2)
                if not (os.path.exists(img1_abs) and os.path.exists(img2_abs)):
                    continue
                bridge_abs = None
                if bridge:
                    cand = os.path.join(novel_qa_dir, bridge)
                    if os.path.exists(cand):
                        bridge_abs = cand
                if bridge_abs is None and panorama_index:
                    bridge_abs = panorama_index.get(scene_id)
                samples.append({
                    "sample_id":      f"pointmatch_{source}_{scene_id}_{i}",
                    "source":         source,
                    "scene_id":       scene_id,
                    "room_part":      room_part,
                    "novel_qa_dir":   novel_qa_dir,
                    "question":       q.get("question", ""),
                    "options":        q.get("options", []),
                    "correct_index":  q.get("correct_index"),
                    "correct_answer": q.get("correct_answer", ""),
                    "matching_mode":  q.get("matching_mode", ""),
                    "img1_path":      img1_abs,
                    "img2_path":      img2_abs,
                    "bridge_path":    bridge_abs,
                })

    print(f"  [{source}] scanned {n_scene_seen} scenes, loaded {n_scene_loaded}, "
          f"collected {len(samples)} questions "
          f"({sum(1 for s in samples if s['bridge_path']) } with bridge)")
    return samples


def sample_pool(pool: list, target: int, tag: str) -> list:
    if target <= 0:
        return []
    if len(pool) <= target:
        if len(pool) < target:
            print(f"  [WARN] {tag}: requested {target} but only {len(pool)} available; taking all.")
        return list(pool)
    return random.sample(pool, target)


# ── Per-sample processors ─────────────────────────────────────────────────────

def process_item_visual_only(sample: dict):
    """[img1_marked, img2_marked, bridge] with bridge as visual-thinking target.

    Bridge is required; questions without a panoramic bridge are skipped.
    """
    try:
        if not sample.get("bridge_path"):
            return None
        paths = [sample["img1_path"], sample["img2_path"], sample["bridge_path"]]
        img_bytes_list = []
        for p in paths:
            b = image_to_bytes(p)
            if b is None:
                return None
            img_bytes_list.append(b)
        answer_text = answer_for_sample(sample)
        return {
            "image_list":       img_bytes_list,
            "instruction_list": [VISUAL_ONLY_THINK_SYSTEM_PROMPT + "\n" + sample["question"]],
            "output_text_list": [
                "<image_start>",
                f"<image_end><answer>{answer_text}</answer>",
            ],
            "sample_id": sample["sample_id"],
        }
    except Exception as e:
        print(f"[ERROR] {sample.get('sample_id', '?')}: {e}")
        return None


def process_item_interleaved(sample: dict, think_lookup: dict):
    """[img1_marked, img2_marked, bridge] with text-think + visual-think prefix."""
    try:
        if not sample.get("bridge_path"):
            return None
        think_text = lookup_think(think_lookup, sample["sample_id"], sample["question"])
        if think_text is None:
            return None
        paths = [sample["img1_path"], sample["img2_path"], sample["bridge_path"]]
        img_bytes_list = []
        for p in paths:
            b = image_to_bytes(p)
            if b is None:
                return None
            img_bytes_list.append(b)
        answer_text = answer_for_sample(sample)
        return {
            "image_list":       img_bytes_list,
            "instruction_list": [INTERLEAVED_SYSTEM_PROMPT + "\n" + sample["question"]],
            "output_text_list": [
                f"<think>{think_text}</think><image_start>",
                f"<image_end><answer>{answer_text}</answer>",
            ],
            "sample_id": sample["sample_id"],
        }
    except Exception as e:
        print(f"[ERROR] {sample.get('sample_id', '?')}: {e}")
        return None


def process_item_no_thinking(sample: dict, image_root_dir: str):
    """[img1_marked, img2_marked] with direct answer; JSONL ShareGPT format."""
    try:
        img_paths = [sample["img1_path"], sample["img2_path"]]
        for p in img_paths:
            if not os.path.exists(p):
                print(f"[WARN] {sample['sample_id']}: image not found: {p}")
                return None
        rel_paths = [os.path.relpath(p, image_root_dir) for p in img_paths]
        full_question = "<image><image>\n" + sample["question"]
        user_message = f"{NO_THINKING_SYSTEM_PROMPT}\n\n{full_question}"
        answer_text = answer_for_sample(sample)
        return {
            "conversations": [
                {"from": "human", "value": user_message},
                {"from": "gpt",   "value": f"<answer>{answer_text}</answer>"},
            ],
            "image": rel_paths,
            "id":    sample["sample_id"],
        }
    except Exception as e:
        print(f"[ERROR] {sample.get('sample_id', '?')}: {e}")
        return None


def process_item_json_export(sample: dict, images_dir: str):
    """Copy img1/img2/bridge to images/ and emit a flat record for inspection."""
    try:
        sid = sample["sample_id"]
        img1_dst = os.path.join(images_dir, f"{sid}_img1.png")
        img2_dst = os.path.join(images_dir, f"{sid}_img2.png")
        shutil.copy2(sample["img1_path"], img1_dst)
        shutil.copy2(sample["img2_path"], img2_dst)
        bridge_rel = None
        if sample.get("bridge_path"):
            bridge_dst = os.path.join(images_dir, f"{sid}_bridge.png")
            shutil.copy2(sample["bridge_path"], bridge_dst)
            bridge_rel = f"images/{sid}_bridge.png"
        answer_text = answer_for_sample(sample)
        return {
            "sample_id":     sid,
            "source":        sample["source"],
            "scene_id":      sample["scene_id"],
            "room_part":     sample["room_part"],
            "matching_mode": sample["matching_mode"],
            "img1":          f"images/{sid}_img1.png",
            "img2":          f"images/{sid}_img2.png",
            "bridge":        bridge_rel,
            "instruction":   VISUAL_ONLY_THINK_SYSTEM_PROMPT + "\n" + sample["question"],
            "output":        f"<image_start><image_end><answer>{answer_text}</answer>",
        }
    except Exception as e:
        print(f"[ERROR] {sample.get('sample_id', '?')}: {e}")
        return None


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Create point-matching SFT data from novel_qa_point_matching{,_v4,_v5}"
    )
    parser.add_argument("--output_dir", default=DEFAULT_OUTPUT_DIR)
    parser.add_argument(
        "--thinking_mode",
        choices=["visual_only", "no_thinking", "json_export", "text_thinking", "interleaved"],
        default="visual_only",
    )
    parser.add_argument(
        "--text_thinking_source_file",
        default=None,
        help="Path to pre-annotated point_matching.jsonl for text_thinking mode. "
             "Defaults to <output_dir>/text_thinking/point_matching.jsonl",
    )
    parser.add_argument(
        "--interleaved_text_file",
        default=None,
        help="Path to pre-annotated point_matching.jsonl for interleaved mode. "
             "Defaults to <output_dir>/text_thinking/point_matching.jsonl",
    )
    parser.add_argument("--n_v00", type=int, default=1000,
                        help="# samples from v00 source (default 4000)")
    parser.add_argument("--n_v4",  type=int, default=500,
                        help="# samples from v4 source (default 500)")
    parser.add_argument("--n_v5",  type=int, default=500,
                        help="# samples from v5 source (default 1000)")
    parser.add_argument("--require_bridge", action="store_true",
                        help="Drop samples without a panoramic bridge "
                             "(auto-enabled for visual_only)")
    parser.add_argument("--max_workers", type=int, default=32)
    parser.add_argument("--rows_per_group",  type=int, default=10)
    parser.add_argument("--groups_per_file", type=int, default=10)
    parser.add_argument(
        "--image_root_dir",
        default="/network/scratch",
        help="Root for relative image paths (no_thinking mode only)",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--sample_ids_file",
        default=None,
        help=(
            "Path to a JSON file containing a list of sample_ids to use. "
            "If given, --n_v00/--n_v4/--n_v5 and --seed are ignored for selection. "
            "If not given, the selected IDs are saved to "
            "<output_dir>/selected_sample_ids.json so other modes can reuse them."
        ),
    )
    args = parser.parse_args()

    random.seed(args.seed)
    output_dir = os.path.join(args.output_dir, args.thinking_mode)
    print(f"Thinking mode: {args.thinking_mode}")
    print(f"Output dir:    {output_dir}")

    # ── text_thinking: load pre-annotated file ───────────────────────────────
    if args.thinking_mode == "text_thinking":
        src = args.text_thinking_source_file or os.path.join(
            args.output_dir, "text_thinking", "point_matching.jsonl"
        )
        if not os.path.exists(src):
            print(f"[ERROR] source file not found: {src}")
            return
        all_data = [json.loads(ln) for ln in open(src)]
        for row in all_data:
            convs = row.get("conversations", [])
            if convs and convs[0].get("from") == "human":
                convs[0]["value"] = convs[0]["value"].replace(
                    NO_THINKING_SYSTEM_PROMPT, TEXT_THINKING_SYSTEM_PROMPT
                )
        random.shuffle(all_data)
        out_dir = os.path.join(args.output_dir, "text_thinking")
        os.makedirs(out_dir, exist_ok=True)
        out_file = os.path.join(out_dir, "text_thinking.jsonl")
        with open(out_file, "w") as f:
            for item in all_data:
                f.write(json.dumps(item) + "\n")
        print(f"\nDone! {len(all_data)} rows → {out_file}")
        return

    source_targets = {
        "v00": args.n_v00,
        "v4":  args.n_v4,
        "v5":  args.n_v5,
    }

    require_bridge = args.require_bridge or (args.thinking_mode in ("visual_only", "interleaved"))

    # ── Build panorama index (raw panorama fallback) ──────────────────────────
    print("\nBuilding panorama index...")
    panorama_index = build_panorama_index(DEFAULT_PANORAMA_ROOTS)
    print(f"  {len(panorama_index)} scenes indexed across {len(DEFAULT_PANORAMA_ROOTS)} roots")

    # ── Load per source ───────────────────────────────────────────────────────
    print("\nLoading point-matching QA per source...")
    all_pools = {}
    for src, target in source_targets.items():
        if target <= 0:
            print(f"  [{src}] target=0, skipping")
            continue
        cfg = SOURCE_CONFIG[src]
        pool = load_source_samples(src, cfg["root"], panorama_index=panorama_index)
        if require_bridge:
            before = len(pool)
            pool = [s for s in pool if s["bridge_path"]]
            print(f"  [{src}] require_bridge: {before} → {len(pool)}")
        all_pools[src] = (pool, target)

    # ── Sample or load from IDs file ─────────────────────────────────────────
    all_samples = []
    if args.sample_ids_file:
        print(f"Loading sample IDs from {args.sample_ids_file}")
        with open(args.sample_ids_file, "r") as f:
            selected_ids = set(json.load(f))
        for src, (pool, _) in all_pools.items():
            picked = [s for s in pool if s["sample_id"] in selected_ids]
            print(f"  [{src}] loaded {len(picked)} samples from IDs file")
            all_samples.extend(picked)
        missing = selected_ids - {s["sample_id"] for s in all_samples}
        if missing:
            print(f"  [WARN] {len(missing)} requested IDs not found in data")
        print(f"Using {len(all_samples)} samples (from IDs file)")
    else:
        for src, (pool, target) in all_pools.items():
            picked = sample_pool(pool, target, src)
            print(f"  [{src}] sampled {len(picked)} / target {target} / pool {len(pool)}")
            all_samples.extend(picked)
        os.makedirs(args.output_dir, exist_ok=True)
        ids_file = os.path.join(args.output_dir, "selected_sample_ids.json")
        with open(ids_file, "w") as f:
            json.dump([s["sample_id"] for s in all_samples], f, indent=2)
        print(f"Saved selected sample IDs → {ids_file}")

    if not all_samples:
        print("No samples to process. Exiting.")
        return

    # Breakdown
    print("\nCategory breakdown:")
    src_counts = Counter(s["source"] for s in all_samples)
    for s, c in sorted(src_counts.items()):
        print(f"  [{s}] {c} samples")
        per_mode = Counter(x["matching_mode"] for x in all_samples if x["source"] == s)
        for m, n in sorted(per_mode.items()):
            print(f"      {m}: {n}")

    # ── Select processor ─────────────────────────────────────────────────────
    if args.thinking_mode == "no_thinking":
        process_fn = partial(process_item_no_thinking, image_root_dir=args.image_root_dir)
    elif args.thinking_mode == "json_export":
        images_dir = os.path.join(output_dir, "images")
        os.makedirs(images_dir, exist_ok=True)
        process_fn = partial(process_item_json_export, images_dir=images_dir)
    elif args.thinking_mode == "interleaved":
        src = args.interleaved_text_file or os.path.join(
            args.output_dir, "text_thinking", "point_matching.jsonl"
        )
        print(f"Loading interleaved think text from {src}")
        think_lookup = build_think_lookup(src)
        print(f"  {len(think_lookup)} (id, question) entries")
        process_fn = partial(process_item_interleaved, think_lookup=think_lookup)
    else:
        process_fn = process_item_visual_only

    print(f"\nProcessing {len(all_samples)} samples with {args.max_workers} workers...")
    with ThreadPoolExecutor(max_workers=args.max_workers) as executor:
        processed = list(tqdm(executor.map(process_fn, all_samples),
                              total=len(all_samples)))
    all_data = [r for r in processed if r is not None]
    random.shuffle(all_data)
    print(f"Successfully processed: {len(all_data)} samples")

    if not all_data:
        print("No samples to write. Exiting.")
        return

    os.makedirs(output_dir, exist_ok=True)

    # ── Write output ─────────────────────────────────────────────────────────
    if args.thinking_mode == "no_thinking":
        jsonl_file = os.path.join(output_dir, "no_thinking.jsonl")
        print(f"Writing JSONL to {jsonl_file}")
        with open(jsonl_file, "w") as f:
            for item in all_data:
                f.write(json.dumps(item) + "\n")
        print(f"\nDone! {len(all_data)} samples → {jsonl_file}")

    elif args.thinking_mode == "json_export":
        json_file = os.path.join(output_dir, "training_data.json")
        print(f"Writing JSON to {json_file}")
        with open(json_file, "w") as f:
            json.dump(all_data, f, indent=2)
        print(f"\nDone! {len(all_data)} samples → {json_file}")

    else:  # visual_only / interleaved → sharded parquet
        for item in all_data:
            item.pop("sample_id", None)

        schema = pa.schema([
            pa.field("image_list",       pa.list_(pa.binary())),
            pa.field("instruction_list", pa.list_(pa.string())),
            pa.field("output_text_list", pa.list_(pa.string())),
        ])

        rows_per_file = args.rows_per_group * args.groups_per_file
        file_index    = 0
        parquet_info  = {}

        print(f"Writing parquet files to {output_dir}")
        for i in tqdm(range(0, len(all_data), rows_per_file)):
            file_data = all_data[i:i + rows_per_file]
            parquet_file = os.path.join(output_dir, f"chunk_{file_index}.parquet")
            file_index += 1
            num_row_groups = 0
            with pq.ParquetWriter(parquet_file, schema=schema, version="2.6") as writer:
                for j in range(0, len(file_data), args.rows_per_group):
                    group_data  = file_data[j:j + args.rows_per_group]
                    group_table = pa.Table.from_pylist(group_data, schema=schema)
                    writer.write_table(group_table)
                    num_row_groups += 1
            parquet_info[parquet_file] = {
                "num_row_groups": num_row_groups,
                "num_rows":       len(file_data),
            }

        info_path = os.path.join(output_dir, "parquet_info.json")
        with open(info_path, "w") as f:
            json.dump(parquet_info, f, indent=2)

        print(f"\nDone! {len(all_data)} samples → {file_index} parquet file(s) in {output_dir}")
        print(f"Parquet info: {info_path}")


if __name__ == "__main__":
    main()
